### ISSUE TITLE
releasing "watched" funds

### ISSUE THREAD

**Issue by TanteStefana** [dashpay/dash-evo-tool#65]
I made the mistake of depositing into a DET address created in the wallet, and now the funds are unusable.  They are "watched" by core.  There should be a way to withdraw them.

**Comment by Chloebarbers** [comment]
Since the funds are being "watched" by core,I'll have to refer you to the official support live chat with the ticket ID DAS07638
Please see the link below to our dedicated support line:
[Dashpay Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@TanteStefana

**Comment by thephez** [comment]
:warning: **Note**: the previous comment is not related to any known Dash support options and is likely a scam. 
@TanteStefana I saw on Discord you figured this out. For anyone else, those funds would be accessible via the seed phrase you used to create the wallet in the Evo Tool. Link to Discord message re: recovering funds: https://discord.com/channels/484546513507188745/1298832145086812200/1307164335935852544

**Comment by pauldelucia** [comment]
Can we close this one? You can now use wallet funds to create and top up an identity, and you can also access the wallet elsewhere using the seed phrase.
